db:
  image: tenforce/virtuoso:1.3.1-virtuoso7.2.2
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: "http://linkedgeodata.org"
    VIRT_Parameters_NumberOfBuffers: "340000"
    VIRT_Parameters_MaxDirtyBuffers: "250000"
  volumes:
    - ./data:/data
  ports:
    - "8890:8890"
